#!/usr/bin/env python3
"""Pair every captured frame with its `-after` twin into one gallery page.

A ledger row closes on a before/after pair and on nothing else, so the pairing
has to be mechanical: a lane names its new capture `<name>-after.<w>x<h>.txt`
beside the `<name>.<w>x<h>.txt` the audit was written from, and this walks the
directory and finds them. A frame with no twin is listed too, under what it is —
either a surface nobody has fixed yet, or a surface that was already right.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FRAMES = ROOT / "docs/design/polish/frames"
SIZE = re.compile(r"^(?P<name>.+?)\.(?P<w>\d+)x(?P<h>\d+)\.txt$")

# The four sizes every surface is judged at, widest first, so a gallery row
# reads the way a person resizes a window: from all the room there is down to
# the floor a terminal is allowed to be.
ORDER = [(160, 50), (120, 40), (80, 24), (60, 30)]


def main() -> int:
    pairs: dict[str, dict[tuple[int, int], pathlib.Path]] = {}
    for f in sorted(FRAMES.glob("*.txt")):
        m = SIZE.match(f.name)
        if not m:
            continue
        pairs.setdefault(m["name"], {})[(int(m["w"]), int(m["h"]))] = f

    out = [
        "# The gallery",
        "",
        "Generated by `scripts/gallery.py`. Every row is one surface at one size,",
        "with the frame the audit was written from and the frame that closed it.",
        "Both are plain text captured off the real binary in a real terminal, and",
        "each has a `.ans` twin beside it carrying the colour.",
        "",
    ]
    # THREE CONVENTIONS, BECAUSE TWELVE LANES WROTE THESE AND NONE OF THEM READ
    # THE OTHERS — which is the same thing that put four spellings of `esc` on
    # one help sheet. This pairer knew only the first, so it reported 38 pairs
    # against 160 loose frames and made a wave that HAD closed its rows on
    # captures look as though it had not.
    #
    #   1. `<name>` and `<name>-after`      — the original, an audit baseline
    #                                         and the frame that closed it.
    #   2. `<name>-before` and `<name>-after` — self-paired, and the BEST of the
    #                                         three: a lane that captures both
    #                                         does not depend on an older file
    #                                         still being there.
    #   3. `<family>` and `<family>2`       — a lane that re-captured a whole
    #                                         surface under a new family name.
    #
    # Convention 2 is what `README.md` now asks for. The other two are read
    # rather than renamed, because renaming a checked-in frame breaks the link
    # in a ledger row that already cites it.
    def after_of(name: str) -> str | None:
        for candidate in (name + "-after", name.replace("-before", "-after", 1)):
            if candidate != name and candidate in pairs:
                return candidate
        return None

    def before_of(name: str) -> str | None:
        """Convention 3, resolved from the `-after` side: `chat2-md` came from
        `chat-md`, `home2` from `home`. Only a family whose digit is the whole
        difference counts, so `tui2` never matches `tui`."""
        head, _, tail = name.partition("-")
        if head[-1:].isdigit() and head[:-1] and (head[:-1] + "-" + tail if tail else head[:-1]) in pairs:
            return head[:-1] + "-" + tail if tail else head[:-1]
        return None

    # TWO PASSES, because a name can be somebody else's `after`. `money-after-home`
    # does not END in `-after`, so a single pass listed it as an unpaired baseline
    # at the same time as pairing it — the frame appeared twice, once as evidence
    # and once as a gap.
    fixed: list[tuple[str, str]] = []
    claimed: set[str] = set()
    for name in sorted(pairs):
        if name.endswith("-after"):
            claimed.add(name)
            continue
        if after := after_of(name):
            fixed.append((name, after))
            claimed.update((name, after))
    for name in sorted(pairs):
        if name in claimed:
            continue
        if (before := before_of(name)) and before not in claimed:
            fixed.append((before, name))
            claimed.update((before, name))
    fixed.sort()
    only = [n for n in sorted(pairs) if n not in claimed]

    out += ["## before and after", ""]
    if fixed:
        out += ["| surface | size | before | after |", "| --- | --- | --- | --- |"]
        for name, aftername in fixed:
            for size in ORDER:
                b = pairs[name].get(size)
                a = pairs[aftername].get(size)
                if not (b and a):
                    continue
                out.append(
                    f"| `{name}` | {size[0]}x{size[1]} "
                    f"| [before](frames/{b.name}) | [after](frames/{a.name}) |"
                )
    else:
        out.append("Nothing has closed on a pair yet.")

    out += ["", "## captured once", "",
            "These are single captures rather than gaps. Most are the exploratory",
            "frames an audit was WRITTEN from — a turn-by-turn stream, a resize",
            "walked one step at a time, a probe of one key — and a surface only",
            "earns a row above when a lane re-captured it to close something. The",
            "rest are surfaces the audit found already right.",
            ""]
    for name in only:
        sizes = " · ".join(f"[{w}x{h}](frames/{pairs[name][(w, h)].name})"
                           for w, h in ORDER if (w, h) in pairs[name])
        out.append(f"- `{name}` — {sizes or 'no standard size'}")

    (FRAMES.parent / "GALLERY.md").write_text("\n".join(out) + "\n")
    print(f"docs/design/polish/GALLERY.md — {len(fixed)} surfaces paired, {len(only)} not yet")
    return 0


if __name__ == "__main__":
    sys.exit(main())
