// Package packed ships a folder of embedded text compressed, and unpacks it on
// the first read.
//
// A folder handed to go:embed lands in the binary verbatim, and prose is the
// most compressible thing codeaf ships: the v3 chat manual alone is a megabyte
// of Markdown that is a megabyte of binary. A folder handed to [Pack] lands as
// one gzip stream, about a third of that, and the text a caller reads back is
// identical byte for byte. The raw folder stays in the repository as the source
// of truth; the archive beside it is generated from the folder by go:generate,
// regenerated by `make build`, and asserted against it by [Verify] in the test
// beside every packed corpus. Nothing is hand-edited.
//
// THE WHOLE FOLDER UNPACKS AT ONCE, ON THE FIRST READ, AND NEVER AGAIN. One
// stream over every file compresses far better than one stream per file — the
// pages of a corpus are written in one vocabulary, and gzip's window can only
// trade on that when they are adjacent — and these corpora are read whole
// anyway: a manual is indexed entire, a roster is parsed entire. Declaring a
// folder reads nothing, so a run that never asks it a question never pays for
// it; `codeaf --version` decompresses none of this.
//
// A [Folder] is deliberately not an [io/fs.FS]. An archive has no directories,
// and a type that half-answers fs.WalkDir is worse than one that never claimed
// to walk. A caller asks for a name, for a pattern, or for the whole list.
//
// The archive is a gzip stream of entries, each one
//
//	uvarint(len(name)) name uvarint(len(data)) data
//
// in [Folder.Names] order, which is sorted. [Pack] writes it and [Folder] reads
// it; it is not a format anything else is entitled to produce.
package packed

import (
	"bytes"
	"compress/gzip"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
)

// unpacks counts every folder this process has decompressed. See [Unpacks].
var unpacks atomic.Int64

// Unpacks is how many packed folders this process has decompressed since it
// started, across every corpus in the binary.
//
// IT EXISTS SO THAT "THE LAUNCH READS NONE OF THIS" CAN BE A TEST. The package
// doc above states that law in prose — declaring a folder reads nothing, and
// `codeaf --version` decompresses none of it — and prose is what a change
// quietly breaks: one manual lookup moved onto the launch path costs a megabyte
// of gunzip before the first frame, and nothing would say so. A caller takes the
// reading either side of the construction it is holding to the law and asserts
// the difference is zero; counting rather than timing is what makes that
// assertion the same assertion on every machine.
func Unpacks() int64 { return unpacks.Load() }

// Folder is one packed folder, still compressed until something reads it.
type Folder struct {
	archive []byte

	once  sync.Once
	files map[string][]byte
	names []string
}

// New names an archive. Nothing is decompressed here, so a package-level
// folder costs a pointer at startup and nothing else.
func New(archive []byte) *Folder { return &Folder{archive: archive} }

// ReadFile returns one file's bytes. The name is the one the file had under
// go:embed — "chat/keys.md", not "keys.md" — so no caller's paths move when a
// folder becomes packed. The returned slice belongs to the caller.
func (f *Folder) ReadFile(name string) ([]byte, error) {
	f.once.Do(f.unpack)
	data, ok := f.files[name]
	if !ok {
		return nil, &fs.PathError{Op: "read", Path: name, Err: fs.ErrNotExist}
	}
	return bytes.Clone(data), nil
}

// Names lists every packed file, sorted, which is the order the folder was
// walked in.
func (f *Folder) Names() []string {
	f.once.Do(f.unpack)
	return slices.Clone(f.names)
}

// Glob returns the packed names matching pattern, in [Folder.Names] order. The
// syntax and the ErrBadPattern are [io/fs.Glob]'s, because that is what the
// callers of a folder were written against.
func (f *Folder) Glob(pattern string) ([]string, error) {
	if _, err := path.Match(pattern, ""); err != nil {
		return nil, err
	}
	var matched []string
	for _, name := range f.Names() {
		if ok, _ := path.Match(pattern, name); ok {
			matched = append(matched, name)
		}
	}
	return matched, nil
}

// unpack decompresses the archive whole, once.
//
// A corrupt archive panics rather than becoming an error every caller has to
// carry. The archive is compiled into the binary and [Verify] reads every byte
// of it in the test beside each corpus, so a corruption that reaches a build is
// a build that could not have passed — it is not a runtime mode.
func (f *Folder) unpack() {
	unpacks.Add(1)
	f.files = map[string][]byte{}
	stream, err := gzip.NewReader(bytes.NewReader(f.archive))
	if err != nil {
		panic("packed: open archive: " + err.Error())
	}
	body, err := io.ReadAll(stream)
	if err != nil {
		panic("packed: read archive: " + err.Error())
	}
	if err := stream.Close(); err != nil {
		panic("packed: close archive: " + err.Error())
	}
	for len(body) > 0 {
		name, rest, err := field(body)
		if err != nil {
			panic("packed: " + err.Error())
		}
		data, rest, err := field(rest)
		if err != nil {
			panic("packed: " + err.Error())
		}
		f.names = append(f.names, string(name))
		f.files[string(name)] = data
		body = rest
	}
}

// field splits one length-prefixed run off the front of an archive body and
// returns it with what is left.
func field(body []byte) ([]byte, []byte, error) {
	length, header := binary.Uvarint(body)
	if header <= 0 || uint64(len(body)-header) < length {
		return nil, nil, errors.New("truncated archive")
	}
	end := header + int(length)
	return body[header:end], body[end:], nil
}

// Pack walks a folder and returns the archive [New] reads. Entry names keep the
// folder's own base name in front — Pack("chat") names "chat/keys.md" — so the
// packed names are the names go:embed gave.
//
// It skips what go:embed skips: a name beginning with "." or "_", and anything
// that is not a regular file. The result is a pure function of the folder's
// bytes — sorted names, fixed level, no timestamps — so regenerating an
// unchanged folder rewrites an identical archive and leaves the tree clean.
// That is what lets `make build` regenerate unconditionally instead of trusting
// a freshness check.
func Pack(root string) ([]byte, error) {
	names, contents, err := walk(root)
	if err != nil {
		return nil, err
	}
	var archive bytes.Buffer
	stream, err := gzip.NewWriterLevel(&archive, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	var header [binary.MaxVarintLen64]byte
	write := func(run []byte) error {
		size := binary.PutUvarint(header[:], uint64(len(run)))
		if _, err := stream.Write(header[:size]); err != nil {
			return err
		}
		_, err := stream.Write(run)
		return err
	}
	for _, name := range names {
		if err := write([]byte(name)); err != nil {
			return nil, err
		}
		if err := write(contents[name]); err != nil {
			return nil, err
		}
	}
	if err := stream.Close(); err != nil {
		return nil, err
	}
	return archive.Bytes(), nil
}

// Verify reports whether an archive still holds exactly what a folder holds,
// name for name and byte for byte. It is what the test beside each packed
// corpus asserts, so a page edited without regenerating fails the build rather
// than shipping yesterday's text.
func Verify(archive []byte, root string) error {
	names, contents, err := walk(root)
	if err != nil {
		return err
	}
	folder := New(archive)
	if packed := folder.Names(); !slices.Equal(packed, names) {
		return fmt.Errorf("packed archive of %s holds %v, the folder holds %v", root, packed, names)
	}
	for _, name := range names {
		data, err := folder.ReadFile(name)
		if err != nil {
			return err
		}
		if !bytes.Equal(data, contents[name]) {
			return fmt.Errorf("packed %s is not the file on disk", name)
		}
	}
	return nil
}

// walk reads a folder the way go:embed would have, and is the single place
// that decides which files are in a corpus and what they are called.
func walk(root string) ([]string, map[string][]byte, error) {
	root = filepath.Clean(root)
	prefix := filepath.Base(root)
	var names []string
	contents := map[string][]byte{}
	err := filepath.WalkDir(root, func(current string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if name := entry.Name(); current != root && (strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if !entry.Type().IsRegular() {
			return nil
		}
		relative, err := filepath.Rel(root, current)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(current)
		if err != nil {
			return err
		}
		name := path.Join(prefix, filepath.ToSlash(relative))
		names = append(names, name)
		contents[name] = data
		return nil
	})
	if err != nil {
		return nil, nil, err
	}
	sort.Strings(names)
	return names, contents, nil
}
